services:
  exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    command:
      - '--path.rootfs=/host'
    restart: 'unless-stopped'
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
