include:
  - ./docker-compose.exporter.yaml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: 'unless-stopped'
    command:
      - '--storage.tsdb.retention.time=6w'
      - '--storage.tsdb.retention.size=5GB'
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./config/targets.json:/etc/prometheus/targets.json
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: 'unless-stopped'
    ports:
     - 3000:3000
    volumes:
      - ./config/grafana:/var/lib/grafana

