global:
  scrape_interval: 15s
scrape_configs:
  - job_name: head
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: nodes
    file_sd_configs:
      - files:
          - targets.json
storage:
  tsdb:
    retention:
      time: 6w
      size: 5GB
